// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZBk9l3CwhjH_kRifxPW0wtSMvgD4pf3I',
    appId: '1:921774918052:web:3a259b5f04ddeeeda95931',
    messagingSenderId: '921774918052',
    projectId: 'pozitivity-9b027',
    authDomain: 'pozitivity-9b027.firebaseapp.com',
    storageBucket: 'pozitivity-9b027.firebasestorage.app',
    measurementId: 'G-00F2VF8X44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWmvub7gWB1hV9DntZQBwC3iXae3xqbc',
    appId: '1:921774918052:android:09e6ca218693e4a5a95931',
    messagingSenderId: '921774918052',
    projectId: 'pozitivity-9b027',
    storageBucket: 'pozitivity-9b027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEfc_dXzfsAgCDsRLwGZT_opviU9w5KcY',
    appId: '1:921774918052:ios:7547438975b84515a95931',
    messagingSenderId: '921774918052',
    projectId: 'pozitivity-9b027',
    storageBucket: 'pozitivity-9b027.firebasestorage.app',
    iosBundleId: 'com.example.pozitivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEfc_dXzfsAgCDsRLwGZT_opviU9w5KcY',
    appId: '1:921774918052:ios:7547438975b84515a95931',
    messagingSenderId: '921774918052',
    projectId: 'pozitivity-9b027',
    storageBucket: 'pozitivity-9b027.firebasestorage.app',
    iosBundleId: 'com.example.pozitivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZBk9l3CwhjH_kRifxPW0wtSMvgD4pf3I',
    appId: '1:921774918052:web:aa4ac4b6f0b1494da95931',
    messagingSenderId: '921774918052',
    projectId: 'pozitivity-9b027',
    authDomain: 'pozitivity-9b027.firebaseapp.com',
    storageBucket: 'pozitivity-9b027.firebasestorage.app',
    measurementId: 'G-06V8VZ0P12',
  );
}
